### ISSUE TITLE
mintinstall: Slow Software Manager Launch

### ISSUE THREAD

**Issue by NeeL21YT** [linuxmint/mint22-beta#112]
When adjusting brightness from the taskbar it's slow in updating the brightness as compared to Ubuntu 24.04 

For the software manager app issue, it takes 20-30 secs to open even if i generate the cache by opening once and closing then trying to open again and its unresponsive when i try to search something quickly as soon as the app opens! It's still better than 21.3 launch time but i hope some improvements can be done!

**Comment by haggen88** [comment]
In my case after generating the cache and displaying the apps, every time I move the Software Manager window it does not respond for a few seconds (approx 10-15 sec.). 

mint@mint:~$ mintinstall
MintInstall: low resolution detected (768px height), limiting window height.
MintInstall: Detected system architecture: 'x86_64'
MintInstall: No new reviews
MintInstall: Deleting old screenshots
Mintinstall startup took 3195.494 ms
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1533, in on_slideshow_timeout
    visible_child = self.banner_stack.get_visible_child()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_visible_child'

But in general a clear decrease in the opening time is observed.

**Comment by mtwebster** [comment]
@haggen88 The error you're getting there should be fixed by linuxmint/mintinstall@eee710ee573f5

@NeeL21YT For me, the software center opens immediately and is fully loaded in about 3-4 seconds - I have a fairly quick machine. For slower/older machines it's unfortunately going to take longer, though for what you're reporting, 20-30 seconds might be expected if you're updating the cache (since there is also downloading occurring), but it should open more quickly than that normally, unless you really have a slow computer (or maybe only a single core?)

You can see if you're getting any errors by running mintinstall this way:
```
DEBUG=1 MINTINSTALL_DEBUG=1 mintinstall
```

Please, in the future, open separate issues for separate bugs
