### ISSUE TITLE
Linux mint beta pilote NVIDIA

### ISSUE THREAD

**Issue by ericwot8** [linuxmint/mint22-beta#120]
Bonjour serait-il possible que vous utilisez la toute dernière carte graphique nvidia je vais vous expliquer. 

Sur Ubuntu quand on ajoute les pilotes bêta de nvidia avec les PPA nous avons accès à la toute dernière technologie NVIDIA la 550 .

C'est vrai que ça sera pas mal que vous ajoutez cette option car je l'ai fait sur Linux la 21.3 ça n'a pas marché je suis toujours resté sur la 5.35 en version alors que j'avais ajouté les PPA beta de nvidia pour avoir la dernière version je voudrais bien que vous le mettez en place ce système pour utiliser la toute dernière technologie en carte graphique merci beaucoup

**Comment by fredcw** [comment]
Translated:

Hello would it be possible that you are using the latest nvidia graphics card I will explain to you.

On Ubuntu when we add the NVIDIA beta drivers with the PPAs we have access to the very latest NVIDIA 550 technology.

It's true that it won't be bad if you add this option because I did it on Linux 21.3 it didn't work I always stayed on version 5.35 even though I added the Nvidia beta PPAs to have the latest version I would like you to set up this system to use the latest graphics card technology thank you very much

**Comment by Angedestenebres** [comment]
Hey :cat: 

Nvidia drivers are provided by Ubuntu repos and latest drivers are 550 on Mint 21.3:

![image](https://github.com/linuxmint/mint22-beta/assets/21110485/e9bc41c7-142b-47e2-a284-d846cb211821)

If 535 only has been suggested, I guess this is related to your device, mainly if you use official PPA from Nvidia that provides latest drivers.

**Comment by Harry-W-Haines-III** [comment]
Moving outside the recommended driver is for advanced users only who can recover from a broken system.  Please keep in mind the 535 driver was updated Thu, 30 May 2024 12:53:28 +0200.
