### ISSUE TITLE
Bluefish editor installation errors

### ISSUE THREAD

**Issue by becker44a** [linuxmint/mint22-beta#129]
I installed the editor "bluefish" from the default repos. Errors messages appeared during the apt-get session.  Subsequent testing of bluefish did not reveal any functional problems.  error messages were:
------------------------------------------------------------
Setting up bluefish (2.2.15-1) ...
/usr/share/bluefish/jsbeautifier/__init__.py:1393: SyntaxWarning: invalid escape sequence '\s'
  self.block_comment_pattern = re.compile('([\s\S]*?)((?:\*\/)|$)')
/usr/share/bluefish/jsbeautifier/__init__.py:1398: SyntaxWarning: invalid escape sequence '\/'
  self.directives_block_pattern = re.compile('\/\* beautify( \w+[:]\w+)+ \*\/')
/usr/share/bluefish/jsbeautifier/__init__.py:1399: SyntaxWarning: invalid escape sequence '\w'
  self.directive_pattern = re.compile(' (\w+)[:](\w+)')
/usr/share/bluefish/jsbeautifier/__init__.py:1400: SyntaxWarning: invalid escape sequence '\s'
  self.directives_end_ignore_pattern = re.compile('([\s\S]*?)((?:\/\*\sbeautify\signore:end\s\*\/)|$)')
/usr/share/bluefish/jsbeautifier/__init__.py:1402: SyntaxWarning: invalid escape sequence '\?'
  self.template_pattern = re.compile('((<\?php|<\?=)[\s\S]*?\?>)|(<%[\s\S]*?%>)')
/usr/share/bluefish/jsbeautifier/__init__.py:1595: SyntaxWarning: invalid escape sequence '\['
  (self.opts.e4x and c == "<" and re.match('^<([-a-zA-Z:0-9_.]+|{[^{}]*}|!\[CDATA\[[\s\S]*?\]\])(\s+[-a-zA-Z:0-9_.]+\s*=\s*(\'[^\']*\'|"[^"]*"|{.*?}))*\s*(/?)\s*>', self.input[self.parser_pos - 1:])) \
/usr/share/bluefish/jsbeautifier/__init__.py:1628: SyntaxWarning: invalid escape sequence '\/'
  xmlRegExp = re.compile('<(\/?)([-a-zA-Z:0-9_.]+|{[^{}]*}|!\[CDATA\[[\s\S]*?\]\])(\s+[-a-zA-Z:0-9_.]+\s*=\s*(\'[^\']*\'|"[^"]*"|{.*?}))*\s*(/?)\s*>')
/usr/share/bluefish/jsbeautifier/unpackers/packer.py:85: SyntaxWarning: invalid escape sequence '\]'
  '[\]^_`abcdefghijklmnopqrstuvwxyz{|}~')
------------------------------------------------------------

Testing in a VirtualBox 6.1.48 Virtual Machine.  Running under Mint 20.3 on an AMD Ryzen 5800H CPU.

Tested the bluefish install in another VM under Ubunto 22.04, and similar errors appeared , so this appears to be an upstream issue.
As always, I will be happy to perform any additional tests that would be helpful.

**Comment by Harry-W-Haines-III** [comment]
Rednotebook is another one that throws a bunch of messages for " SyntaxWarning: invalid escape sequence"  How that was missed by the package maintainers ...

**Comment by rcalixte** [comment]
These are artifacts due to Python 3.12. Canonical/Ubuntu opted to switch to Python 3.12 ahead of releasing 24.04 while Debian just recently migrated Python 3.12 to the Testing branch on July 7. These warnings should not impact the execution of the application(s) but will be visible until the changes are made to the individual upstream applications. Given that these applications are unlikely to see backports, these artifacts are likely to remain until the next version of Ubuntu. There is still a chance for it to be fixed upstream before the next Stable release of Debian though. If there isn't a bug report upstream, you should report the project(s) where the changes need to be made.

**Comment by Harry-W-Haines-III** [comment]
@rcalixte Thank you for the detailed explanation.
