### ISSUE TITLE
ubiquity: Installer detects keyboard as German while it's Switzerland/German

### ISSUE THREAD

**Issue by skirmess** [linuxmint/mint22-beta#142]
The installer of Mint 22 beta asked me to press `q`, then `z`. After that it assumed that it's a German keyboard layout. ~This is on an old HP laptop.~

Last time I installed Mint 21, although on a normal PC, it asked me to press one of like 5 keys and correctly identified the keyboard layout as Switzerland/German. The key I pressed there was `*`.

Edit:  I tried it on the other PC too and it behaves the same. Just checking `q` and `z` isn't a good idea as many keyboard layouts have these two keys at the same place but aren't German.

**Comment by skirmess** [comment]
Wikipedia has list of all the [QWERTZ variants](https://en.wikipedia.org/wiki/QWERTZ#Variants)

**Comment by clefebvre** [comment]
This is a bug in ubiquity, possibly even in debian-installer (which ubiquity is based on). There's a lot of technical debt for us in this installer and this is one of the bugs which we've seen in there for years.

I'll close it as upstream since it's not something we're likely to fix. Down the line we'll eventually move to our own installer, live-installer, where these issues are absent.

https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1419167
