### ISSUE TITLE
l10n: Wrong German Localization when authenticating software install

### ISSUE THREAD

**Issue by dohst123** [linuxmint/mint22-beta#145]
1. Click on a .deb package to install
2. Click on "Paket installieren"
3. Windows pops up for authentication of installation. Title is in English rather than in German ("To install this package, you need to authenticate")
![Bildschirmfoto vom 2024-07-10 09-17-16](https://github.com/linuxmint/mint22-beta/assets/61592324/9a970ef1-d09b-4590-909a-21e0a13db83c)

**Comment by clefebvre** [comment]
![image](https://github.com/user-attachments/assets/fcf5ff10-d4c6-408d-944b-07ca9fe90cdf)

**Comment by clefebvre** [comment]
^^ The software is localized. The translation seems to be complete. It works in French also...

**Comment by clefebvre** [comment]
![image](https://github.com/user-attachments/assets/aa890ed3-e39b-4885-a37a-9196e08c3363)

Reproduced.

**Comment by clefebvre** [comment]
![image](https://github.com/user-attachments/assets/9a9603b4-7907-4f15-bcba-d5fef2480335)

This is really weird. I'm not quite sure what's going on. I see a couple of things..

- After installing in German, I can reproduce the issue.
- Adding French and loging out and back in, I still have the issue.
- Adding full French support via mintlocale (with language packs, set language as system language, and full reboot) I get it to work.
- Doing the same for German, it works as well

**Comment by clefebvre** [comment]
I think it needs the language-pack to be installed. The language needs to be set as the system language (because aptdaemon runs as a service), and because it runs on the system bus, it's not enough to just logout, you need a reboot.

**Comment by clefebvre** [comment]
I'll do more testing on this tomorrow.

**Comment by clefebvre** [comment]
I can't reproduce this anymore.

This is after a fresh install in German: 

![image](https://github.com/user-attachments/assets/64e60302-ade3-4c32-916d-6b1b25f1114e)

**Comment by clefebvre** [comment]
Something is seriously wrong in this :)

A few more elements.. I did this:

- Add FR to a DE installation, set it as user/system locales and reboot. <-- without any FR langpacks
- Try to install a .deb -> The first msgid (the one in bold) is in French, but the rest is in English. Very weird.
- Hit Cancel. Hit install again.. -> Everything's in English this time.

I'm not sure what to do here because the components at play aren't really ours:

- aptdaemon is upstream but it's abandoned more or less
- gnome-polkit is upstream but same thing.. we could really do with having our own agent

I think it's only a matter of time before we take over these components but it hasn't been decided yet.

**Comment by clefebvre** [comment]
More info. I see that the langpacks provide .mo for aptdaemon and polkit-gnome-1... 

So I install the FR langpacks and reboot.

- Try to install the .deb, this time everything's in French.
- Hit Cancel, do it again, this time the dialog is still in French, but the bold string is in English (same as this original bug report).

This shows two things:

- the GNOME polkit agent used by Cinnamon needs the language packs (and a reboot) for the dialog to be localized
- there's a bug somewhere in the agent and/or aptdaemon which results in only the first pkexec call to have a properly translated title string

I'm going to leave it at this because the more I look at this the more I just want to fork it properly and move it all away from language packs completely. This is not something that should be done during the BETA though.

I'll add this to our roadmap.
