### ISSUE TITLE
cinnamon: On restart, brightness shows 6%; however, the brightness of the display is very bright (perhaps 100%)

### ISSUE THREAD

**Issue by ovari** [linuxmint/mint22-beta#161]
1. Set Brightness: 6%
2. Restart computer
3. Brightness still shows 6%; however, the display is very bright. Workaround, move the brightness slider left and right to activate 6%

![image](https://github.com/user-attachments/assets/8886efbd-ff8c-460e-ae77-06953db5b08e)

Dual monitor setup.

Non-laptop display set as Primary.

![image](https://github.com/user-attachments/assets/c94bccb7-0f2f-4758-84f8-f5dfc3ead19f)

Thank you

**Comment by clefebvre** [comment]
This requires more troubleshooting. I don't think the issue is with Cinnamon.

I set the brightness and sound volume to 25% here on a macbook pro. The settings as well as actual brightness and volumes persist through a logout/login and even a reboot.

My understanding is that Cinnamon just acts as a client to system components here (pulseaudio/pipewire for the sound, xrandr? for the brightness) and it is these components which are responsible for the persistence and the application of these settings.

In the case of the brightness it's even more visible since it doesn't just need to apply to the user session, but also to the login screen.

This needs more troubleshooting to identify the responsible component and then a bug should be reported upstream against it.
