### ISSUE TITLE
Snap and plans for the stable release

### ISSUE THREAD

**Issue by FranBarInstance** [linuxmint/mint22-beta#180]
I have been testing the beta in virtualbox, I have not found any problem, the thing is that I would like to install on my computers this version, since I need at least a kernel 6.6 or higher.

Then I have three questions:

Is there any commitment from the linux mint team not to use Snap? It would be a problem for me if Snap was mandatory at some point.

Once the beta period is over will I have to reinstall another iso or will I be able to upgrade?

How far away is the stable version?

Thanks

**Comment by JesseLeePalser** [comment]
1. Not sure about "Snap"
2. In-place upgrade from Beta to Retail through Update Manager
3. End of July

**Comment by ewangi** [comment]
Linux Mint is not a fan of Snap and it was disabled by default as of Linux Mint 20. See here: https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html

The way that Mint operates is that the final version is only released when a certain level of quality is reached after the beta version, and therefore there is no specific date attached to the release of the final version. It is usually a couple to a few weeks, but there are quite a number of issues to resolve with this release so it may take a while.

Given that this issue is not an outstanding bug, I would recommend that you close it.

**Comment by FranBarInstance** [comment]
I already have it installed on an older computer, the installation went smoothly and everything seems to work fine.

Thanks

**Comment by JosephMcc** [comment]
This issue tracker is meant for tracking bugs for the beta. It's helpful to the devs if it can be kept to that. Your questions could be answered pretty easily on the Mint forums or just doing a search online.
