### ISSUE TITLE
Nvidia 545 Driver not in Driver Manager

### ISSUE THREAD

**Issue by DigitalArchon** [linuxmint/mint22-beta#185]
I just tried the beta on an ASUS laptop with a 3080 GPU. On 21.3 the Driver Manager gives me 4 options, 535, 545, 470 and Nouveau.

On beta 22 I only get 535, 470 and Nouveau.

I find 545 fixed a lot of frame rate and stuttering issues I was getting on 535, so I'm hoping it wasn't intentionally left out.

**Comment by JesseLeePalser** [comment]
Hi,

Duplicate of my bug request below:
https://github.com/linuxmint/mint22-beta/issues/106

Jesse Lee

**Comment by DigitalArchon** [comment]
Hey. I see you closed yours, but I'm not certain the issue was correctly resolved. The issue isn't that the driver is particularly old, as they do receive updates within a version range, but regarding the features of the driver. Even if the 545 driver's latest update is weeks older than the 535 driver, it still has newer features that 535 doesn't.

So by no longer offering 545, anything that benefits from the new features and fixes in that driver series will lose out. In my case if I do upgrade to Mint 22, I'd need to manually install the newer series of drivers (545 or above), or several of my games will be almost unplayable.

**Comment by MiZoG99** [comment]
535 is kind of long-term supported, still gets updated while 545 has been dropped by nvidia and not updated since last November. 550 is the current "production branch" driver, is available in Ubuntu repos but hasn't appeared in Driver Manager yet.
Install it in the cmd with sudo apt install nvidia-driver-550. I believe sooner or later 550 will be listed as an option. Ubuntu upstream (24.04) defaults to 535 and does not list 545 either.

**Comment by DigitalArchon** [comment]
Fair enough. I didn't realise 550 was in the repos and could be installed that easily. Figured I'd have to download from the website.

I'll close this, and hopefully 550 will come to the driver manager soon!
