### ISSUE TITLE
plymouth: LUKS boot incorrect keymap

### ISSUE THREAD

**Issue by AttilaLL** [linuxmint/mint22-beta#19]
IF Mint 22 is installed with LUKS encryption and different language and keyboard map than English it will show incorrect key-map during boot ("ttwi" but it seems to be just a part of the text since it is cut out) and then it is impossible to correctly fill the encryption password.

**Comment by AttilaLL** [comment]
Witch English language and key-map it will just show no for key-map but it is possible to enter correct password without problems. (the red bar is just me censoring length of my password)
![IMG_20240630](https://github.com/linuxmint/mint22-beta/assets/168548232/20b454b4-c2c0-4033-9263-46ee07b94db0)

**Comment by ArrayBolt3** [comment]
This is an issue caused because of a change in Plymouth. I had to fix this in multiple official Ubuntu flavors for the 24.04 cycle, and it appears to be affecting Mint too.

The bug report in Ubuntu where this was fixed is here: https://bugs.launchpad.net/bugs/2063895

Basically what's happening is that in order to show the keyboard layout that should be used to decrypt the disk, Plymouth takes a slice out of a file called "keymap-render.png" and displays it. Apparently some Plymouth update added new keymaps to the list of supported keymaps, and thus the keymap-render.png file changed in a way incompatible with the old file. Now the spot in the file that used to display the "us" keyboard layout now displays "no" instead. There are other similar mixups as a result of image slices being shifted.

The official Ubuntu spinner theme has the correct keymap-render.png file for this version of Plymouth. You should be able to copy /usr/share/plymouth/themes/spinner/keymap-render.png into the Plymouth theme for Linux Mint, then regenerate the initramfs. That should resolve the issue.

**Comment by clefebvre** [comment]
Thanks @ArrayBolt3 !! You've done all my analysis work for me there :)

**Comment by clefebvre** [comment]
Fixed in ubuntu-system-adjustments 2024.07.17.1.
