### ISSUE TITLE
Cannot install mint-meta-codecs during offline installation

### ISSUE THREAD

**Issue by MiZoG99** [linuxmint/mint22-beta#32]
Checked it twice. I opted for installation of multimedia codecs while installing Mint offline.
Both times I was prompted upon boot by mintreport to install multimedia codecs. And indeed media codecs had not been installed.

I'd expect to be able to install codecs during an offline installation or otherwise the option should have been greyed-out like the option to install system updates during installation was greyed-out. 

This is actually how I noticed this [issue](https://github.com/linuxmint/mint22-beta/issues/10)

**Comment by clefebvre** [comment]
I agree. It's not ideal.

What you're seeing here isn't really just the codecs, it's also the free drivers. I really don't like how this is presented but it's a compromise which comes from the way ubiquity is designed.

I'm going to mark this as wontfix for now because short term it's not an important issue and long term we'll probably move towards live-installer.
