### ISSUE TITLE
Packages that were is Mint 21.3, not in mint22-beta

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/mint22-beta#47]
awf-gtk2
isomaster
ttf-anonymous-pro

I did an install with a known list of packages.  Out of 100's these 3 were not available.

**Comment by Fantu** [comment]
There is awf-gtk source that generate [awf-gtk3](https://packages.ubuntu.com/noble/awf-gtk3) and [awf-gtk4](https://packages.ubuntu.com/noble/awf-gtk4)
https://tracker.debian.org/pkg/isomaster - was removed
ttf-anonymous-pro was a transition metapackage for [fonts-anonymous-pro](https://packages.ubuntu.com/noble/fonts-anonymous-pro)

**Comment by pilatomic** [comment]
you can add freecad to that list

**Comment by Fantu** [comment]
freecad was removed from Debian testing for RC bug: https://tracker.debian.org/pkg/freecad
is missed in ubuntu 24.04 (https://launchpad.net/ubuntu/+source/freecad), I suppose for similar issue not solved in time
package is still maintained and probably will be return to testing before debian 13 freeze, about 24.04 there were some problems due to the bigger transition in the middle (64 bit time_t) and some transitions made before Debian to fit them into the Ubuntu 24.04 release but which caused problems with software not yet ready for those transitions (like that of python 3.12)

**Comment by Harry-W-Haines-III** [comment]
Pinta was also removed but it is available as an AppImage.  These things happen when the  LTS base changes and the some of the corresponding dependent packages won't work.  Try looking for AppImage replacements of your missing packages.

**Comment by Fantu** [comment]
pinta was removed https://tracker.debian.org/pkg/pinta
the problem was the move to dotnet runtime, someone tried to package dotnet for Debian and derivates but failed because it was not compliant with the [DFSG](https://www.debian.org/social_contract#guidelines)

**Comment by clefebvre** [comment]
@Harry-W-Haines-III said it all, pkgs come and go between package bases.
