### ISSUE TITLE
cinnamon: Keyboard layout - some options are not translated

### ISSUE THREAD

**Issue by Angedestenebres** [linuxmint/mint22-beta#69]
As said in the title, see screens:

![VirtualBox_Linux Mint 22_03_07_2024_11_54_50](https://github.com/linuxmint/mint22-beta/assets/21110485/c450b459-fa12-4615-8736-c10024baacee)
![VirtualBox_Linux Mint 22_03_07_2024_12_11_14](https://github.com/linuxmint/mint22-beta/assets/21110485/42c41dfd-1c25-46fd-bc63-13bd723000e6)

**Comment by adrianlopezgalera** [comment]
Some strings are also missing in Spanish:

![Captura de pantalla de 2024-07-03 13-15-44](https://github.com/linuxmint/mint22-beta/assets/77041822/c04ac7a1-4b61-4c78-b270-d82547342de7)

**Comment by clefebvre** [comment]
Ok, I'll have to check the code, I think this is Xorg and upstream from us.. I'll get back to you on this.

**Comment by clefebvre** [comment]
Confirmed, this is upstream from us and specific to Ubuntu (i.e. it works upstream from them).

It belongs to xkeyboard-config which is translated upstream (note sure if that's the right link, but that shows up to date translations https://github.com/gemian/xkeyboard-config/blob/bookworm/po/fr.po#L4579).

Ubuntu has its own unique specificity when it comes to language packs. It removes translations from core packages and adds them to language-pack packages.

The problem here is that the translations from xkeyboard-config are provided by language-pack-fr-base, and they're not up to date.

https://packages.ubuntu.com/source/noble/language-pack-fr-base
