### ISSUE TITLE
incorrect/missing Qsynth system tray icon

### ISSUE THREAD

**Issue by arxo** [linuxmint/mint22-beta#77]
Compared to LM 21.3 (green) the beta for LM 22 (red) does not show a proper system tray icon for Qsynth:
![image](https://github.com/linuxmint/mint22-beta/assets/43294041/822b454e-d5e1-4dd7-b41f-0ad4c8e558ad)
I tried various themes, like Mint-Y and Yaru, all have the same issue.

How to reproduce:
- sudo apt install qsynth
- run qsynth
- in options enable system tray icon

**Comment by clefebvre** [comment]
This is upstream from us.

It looks like it's fixed in the version 1.0.0 upstream:

https://github.com/rncbc/qsynth/commit/1b8282069478ea1fe9831d1fa41e7daabbdb5085
https://github.com/rncbc/qsynth/commit/1392081837dbe5731aab354f0f7d55faba71e6a0

You can get 1.0.0 via Flatpak, or build it from source.
